name: Publish

on:
  push:
    branches:
      - main
      - ci

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Build
        run: |
          cargo build --release

      - name: Upload built binary
        uses: actions/upload-artifact@v2
        with:
          name: cli-files
          path: target/release/swc-dev

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: cli-files

      - name: List files
        run: ls -R
